@startuml
skinparam usecaseBorderColor #f84c66ff
skinparam usecaseFontColor #24273a
skinparam usecaseBackgroundColor #ed8796
skinparam usecaseFontStyle bold
skinparam usecaseFontSize 20
skinparam componentStyle rectangle
skinparam componentBorderColor #8aadf4
skinparam componentFontColor #7dc4e4
skinparam componentFontStyle bold
skinparam componentBackgroundColor #363a4f 
skinparam backgroundColor transparent
skinparam roundCorner 30
skinparam rectangleBorderColor #c6a0f6
skinparam rectangleFontColor #c6a0f6
skinparam rectangleFontStyle bold
skinparam rectangleFontSize 25
skinparam rectangleRoundCorner 10
left to right direction
skinparam componentFontSize 20

skinparam arrowColor #f5bde6
skinparam arrowThickness 2
skinparam edgeFontColor #f5a97f
skinparam edgeLineWidth 2

(I-frame) as a1
[B-frame] as a2
[B-frame] as a3
rectangle P-frame as a4 {

}
[B-frame] as a5
[...] as a6
(I-frame) as a7
[...] as a8
a1 --> a2
a2 --> a3
a3 --> a4
a4 --> a5
a5 --> a6
a6 --> a7
a7 --> a8


@enduml